In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1]+arr[2])

5


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,2])

3


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,2])

7


In [11]:
import numpy as np
arr=np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,0]]])
print(arr[0,1,2])

5


In [12]:
import numpy as np
arr=np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,0]]])
print(arr[1,0,1])

6


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0:4])

[1 2 3 4]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]


In [16]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,0:3])

[5 6 7]


In [17]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0:2,0:2])

[[1 2]
 [5 6]]


In [19]:
import numpy as np
arr=np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,0]]])
print(arr[0:2,0:2,0:2])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
import numpy as np
arr=np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,0]]])
print(arr[0,1,0:3])

[3 4 5]


In [22]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(2, 3, 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
