In [2]:
import numpy as np
arr=np.array([1,2,3])
print(arr+10)

[11 12 13]


In [3]:
import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([1,2,3])
print(arr1+arr2)

[[11 22 33]
 [41 52 63]]


In [20]:
import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([1,2,3])
print(arr1-arr2)

[[ 9 18 27]
 [39 48 57]]


In [21]:
import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([1,2,3])
print(arr1*arr2)

[[ 10  40  90]
 [ 40 100 180]]


In [9]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.dot(arr1,arr2))

32


In [10]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1@arr2)

[[19 22]
 [43 50]]


In [22]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.mean(arr))

30.0


In [23]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
print(np.mean(arr1))

2.5


In [24]:
import numpy as np
arr1=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [25]:
import numpy as np
arr1=np.array([10,20,30,40,50])
print(np.max(arr))

50


In [26]:
import numpy as np
arr1=np.array([10,20,30,40,50])
print(np.min(arr))

10


In [27]:
import numpy as np
arr1=np.array([10,20,30,40,50])
print(np.std(arr))

14.142135623730951


In [31]:
import numpy as np
print(np.sqrt(10))

3.1622776601683795


In [32]:
import numpy as np
print(np.sqrt(16))

4.0


In [33]:
import numpy as np
print(np.pi)

3.141592653589793


In [11]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(np.linalg.det(arr))

-2.0000000000000004


In [12]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.sum(axis=0))

[5 7 9]


In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.sum(axis=1))

[ 6 15]


In [19]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([5,6])
print(np.linalg.solve(arr1,arr2))

[-4.   4.5]
